[package]
name = "mycelium-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mycelium-core = { path = "../mycelium-core" }
mycelium-types = { path = "../mycelium-types" }
anyhow.workspace = true

[dev-dependencies]
async-trait.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
